# Generated by Django 4.2.1 on 2024-03-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0008_alter_director_d_img_alter_director_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="director",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.director"
            ),
        ),
    ]
