# Generated by Django 4.2.1 on 2024-03-27 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_alter_movies_director"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movies",
            name="yt_trailer_dislike",
        ),
    ]
