# Generated by Django 5.0.4 on 2024-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movies_yt_trailer_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imdb_meta',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
