# Generated by Django 5.0.4 on 2024-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movies_imdb_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='yt_trailer_dislike',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdb_meta',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
