# Generated by Django 5.0.4 on 2024-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_movies_imdb_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imdb_meta',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
