# Generated by Django 5.0.4 on 2024-04-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_movies_imdb_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=30)),
                ('Cast_link', models.URLField()),
                ('Cast_img', models.FileField(blank=True, null=True, upload_to='images/')),
                ('insta_followers', models.IntegerField(blank=True, default=0)),
                ('Cast_insta', models.URLField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('about', models.CharField(blank=True, max_length=450)),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='stars',
        ),
        migrations.AddField(
            model_name='movies',
            name='Cast',
            field=models.ManyToManyField(to='movies.cast'),
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
