# Generated by Django 5.0.4 on 2024-04-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_cast_remove_movies_stars_movies_cast_delete_star'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name_plural': 'Movies'},
        ),
        migrations.RemoveField(
            model_name='movies',
            name='yt_trailer_dislike',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='yt_trailer_like',
        ),
    ]
