# Generated by Django 5.0.4 on 2024-04-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_movies_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='link',
            new_name='Imdb_link',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='outline',
            new_name='Plot',
        ),
    ]
