# Generated by Django 5.0.4 on 2024-04-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_rename_link_movies_imdb_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='Imdb_link',
            new_name='IMDb_link',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='imdb_meta',
            new_name='Predicted_Rating',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='yt_trailer_url',
            new_name='Youtube_trailer_link',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='yt_trailer_views',
            new_name='Youtube_trailer_views',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='yt_trailer_title',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='yt_trailer_uploader',
        ),
    ]
