# Generated by Django 5.0.4 on 2024-04-09 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_rename_imdb_link_movies_imdb_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='d_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Cast',
            field=models.ManyToManyField(blank=True, to='movies.cast'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Youtube_trailer_views',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.director'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movies.genre'),
        ),
    ]
