# Generated by Django 5.0.4 on 2024-04-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_alter_movies_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Youtube_trailer_views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
