# Generated by Django 5.0.4 on 2024-04-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_movies_youtube_trailer_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='producer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movies',
            name='writer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
