# Generated by Django 5.0.4 on 2024-04-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_alter_movies_director_movies_producer_movies_writer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast_n_Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=30)),
                ('c_insta', models.URLField(blank=True, null=True)),
                ('insta_followers', models.IntegerField(blank=True, default=0)),
                ('c_score', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='Cast',
        ),
        migrations.AlterField(
            model_name='movies',
            name='Youtube_trailer_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='movies',
            name='Cast_n_Crew',
            field=models.ManyToManyField(blank=True, to='movies.cast_n_crew'),
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
