# Generated by Django 5.0.4 on 2024-04-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_cast_n_crew_remove_movies_cast_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='ph_credit',
            new_name='total_cscore',
        ),
    ]
