# Generated by Django 5.0.4 on 2024-04-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_remove_movies_cast_n_crew_movies_cast_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast_n_crew',
            old_name='c_score',
            new_name='i_score',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='weight',
            new_name='g_score',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='total_cscore',
            new_name='c_score',
        ),
        migrations.AddField(
            model_name='movies',
            name='p_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='v_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
