# Generated by Django 5.0.4 on 2024-04-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_rename_c_score_cast_n_crew_i_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Predicted_Rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
