# Generated by Django 5.0.4 on 2024-04-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_alter_movies_predicted_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Predicted_Rating',
            field=models.FloatField(null=True),
        ),
    ]
