# Generated by Django 5.0.4 on 2024-04-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_alter_genre_g_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast_n_crew',
            name='i_score',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
