# Generated by Django 5.0.4 on 2024-04-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0036_alter_cast_n_crew_i_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast_n_crew',
            name='i_score',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6),
        ),
    ]
