# Generated by Django 5.0.4 on 2024-04-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0037_alter_cast_n_crew_i_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='IMDb_link',
            field=models.URLField(blank=True),
        ),
    ]
