# Generated by Django 5.0.4 on 2024-04-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0038_alter_movies_imdb_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
