# Generated by Django 5.0.4 on 2024-04-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0041_alter_movies_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='writer',
        ),
        migrations.AddField(
            model_name='movies',
            name='directors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movies',
            name='producers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movies',
            name='writers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='movies',
            name='cast',
        ),
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
