# Generated by Django 5.0.4 on 2024-04-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0042_remove_movies_director_remove_movies_producer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast_n_crew',
            name='i_score',
            field=models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=20),
        ),
    ]
