# Generated by Django 5.0.4 on 2024-04-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0043_alter_cast_n_crew_i_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast_n_crew',
            name='i_score',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='genre',
            name='g_score',
            field=models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=20),
        ),
    ]
