# Generated by Django 5.0.4 on 2024-04-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0044_alter_cast_n_crew_i_score_alter_genre_g_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='p_score',
        ),
        migrations.AddField(
            model_name='movies',
            name='g_score',
            field=models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=20),
        ),
    ]
