# Generated by Django 5.0.4 on 2024-04-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0047_alter_movies_g_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='g_score',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=20),
        ),
    ]
