# Generated by Django 5.0.4 on 2024-04-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0050_alter_genre_g_score_alter_movies_g_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='g_score',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
    ]
