# Generated by Django 5.0.4 on 2024-04-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0052_alter_movies_g_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='g_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
