# Generated by Django 5.0.4 on 2024-04-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0053_alter_movies_g_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='v_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
