# Generated by Django 5.0.4 on 2024-04-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0054_alter_movies_v_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='v_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
