# Generated by Django 5.0.4 on 2024-05-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0057_alter_movies_v_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='c_insta',
            field=models.URLField(blank=True, null=True),
        ),
    ]
