# Generated by Django 5.0.4 on 2024-05-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0058_movies_c_insta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='c_insta',
            new_name='c1_insta',
        ),
        migrations.AddField(
            model_name='movies',
            name='c2_insta',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='c3_insta',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='c4_insta',
            field=models.URLField(blank=True, null=True),
        ),
    ]
