# Generated by Django 5.0.4 on 2024-05-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0059_rename_c_insta_movies_c1_insta_movies_c2_insta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='c_score',
            new_name='c1_followers',
        ),
        migrations.AddField(
            model_name='movies',
            name='c2_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='c3_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='c4_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='f_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
