# Generated by Django 5.0.4 on 2024-05-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0060_rename_c_score_movies_c1_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='f_score',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3),
        ),
    ]
