# Generated by Django 5.0.4 on 2024-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0061_alter_movies_f_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Youtube_trailer_views',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='c1_followers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='c2_followers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='c3_followers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='c4_followers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
