# Generated by Django 5.0.4 on 2024-05-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0062_alter_movies_youtube_trailer_views_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cast_n_Crew',
        ),
    ]
