# Generated by Django 5.0.4 on 2024-05-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0063_delete_cast_n_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='about',
        ),
    ]
