# Generated by Django 5.0.4 on 2024-05-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0064_remove_genre_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genres',
        ),
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.CharField(default=0, max_length=600),
            preserve_default=False,
        ),
    ]
