# Generated by Django 5.0.4 on 2024-05-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0065_remove_movies_genres_movies_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
