# Generated by Django 5.0.4 on 2024-05-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0066_alter_movies_genres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
